### ISSUE TITLE
Unify & Prettify The Admin UIs

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#3614]
After looking to the Admin UIs, I found there 're a lot of improvements should be made to polish the overall UI and make them  have the same look and feel, I will add all the admin pages and categorize them by module name to keep track all the changes that I will made

Seems all the Orchard Core team are dev and no one is UI/UX specialist, @sebastienros I will take the initiative on this if you don't mind and this should go before the 1.0.0 to make Orchard Core Admin looks cool & sexy 😄 

- [x] Add breadcrumb to the admin site pages #3687
- [x] Organize headers in the admin site pages #3688
- [x] Make Tenants page pretty #4155
- [x] Prettify Features page #4175
- [x] Prettify Recipes page #4178
- [x] Prettify Content Types page #4213
- [x] Prettify Content Parts page #4212
- [x] Prettify Roles page #4238
- [x] Prettify the Users page #4239
- [ ] Deployment steps cards should be height equal #4281
- [x] Prettify Queries page #4303
- [x] Prettify the Admin Menus page #4304
- [x] Tenants: Select all #4306
- [x] Content items: Bulk actions and Filters UX #4358
- [ ] Ability to make the alerts dismiss able #4236
- [x] Implement new admin UI everywhere #4747

**Comment by sebastienros** [comment]
We all know @Skrypt sucks at html

**Comment by sebastienros** [comment]
But OC looks cool already! Make it awesome if you want, but talk with everyone before starting huge changes.

**Comment by hishamco** [comment]
I knew it looks good, what I plan to change is unify all the pages with the same styles, because what I see is many pages are different from others in terms of headers, content organization, button styles .. etc

I can show you some screenshots to prove what i'm talking about

**Comment by deanmarcussen** [comment]
Be great if we had a shared scss variables file somewhere that all the modules could pull from

**Comment by Skrypt** [comment]
Bootstrap 4 is the shared framework for all things! We should try to use it properly simply. We should do the changes one part of UI at a time. I'm pushing updates here and there when I find time but that's also the work of everyone to try to follow BS4 documentation and use the proper elements.

**Comment by hishamco** [comment]
That's why I opened this issue to scan all the pages across and make them have the similar look and feel

**Comment by deanmarcussen** [comment]
> Bootstrap 4 is the shared framework for all things! We should try to use it properly simply. 

So all modules should import the bootstrap variables file when building sass and make good use of those variables

**Comment by sebastienros** [comment]
@hishamco if you see some oddities please file bugs with the screenshots, that will help people fix them in parallel. If there are common patterns to apply we should document them so we can reference to it when necessary.

**Comment by Skrypt** [comment]
@deanmarcussen Not a bad idea. Need to see what would be the changes to do with the gulp pipeline to make that happen.

**Comment by hishamco** [comment]
There's two work items not finished yet!!
