### ISSUE TITLE
Suggestion: Global and Per user Admin settings

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#4659]
Add some settings related to the Admin UI Experience.

Examples:

- [ ]  Allow to set the upper left Logo: #5920
- [ ]  Custom Head: #5920
- [X] Enable/Disable a Search input above the admin menu to quickly filter the menus: #4674
- [X] Specify in which Zone you want to place the Titles (Top or Content): #7867
- Enable/Disable if you want to add an avatar next to the Username.
- Enable/Disable if the other menu items are collapsed when another is expanded.

Some of them could be 'per user' settings (like the timezone):
- Admin culture: #6525

That would be great if there was a Profile section in the admin for this (may be a dropdown menu on the upper right username).

**Comment by agriffard** [comment]
Add a Search input in the top bar that redirects to the content items page with this filter.
This could be an autocomplete that calls in ajax the indexed contents and directly suggest existing ones.

**Comment by hishamco** [comment]
> Enable/Disable if you want to add an avatar next to the Username.

I'm already started this in the Gravatar module

> Admin culture.

This is already discusses in another issue

Overall I like some if not all the enhancements

**Comment by sebastienros** [comment]
Lots of good ideas, for different modules/features. Maybe split it in as many issues.

**Comment by agriffard** [comment]
Closing. Will make separate issues if needed.
