### ISSUE TITLE
Add source code docs

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5095]
Adding a documentation for `public` and `protected` members for OC, this including:

- [ ] Add OC abstractions docs
- [ ] Add OC admin abstractions docs
- [ ] Add OC admin menu abstractions docs
- [ ] Add OC graph QL abstractions docs
- [ ] Add OC content localization abstractions docs
- [ ] Add OC content management abstractions docs
- [ ] Add OC content types abstractions docs
- [x] Add OC data abstractions docs #4918
- [ ] Add OC deployment abstractions docs
- [ ] Add OC display management abstractions docs
- [ ] Add OC dynamic cache abstractions docs
- [x] Add OC email abstractions docs #4919
- [ ] Add OC feeds abstractions docs
- [ ] Add OC file storage abstractions docs
- [ ] Add OC indexing abstractions docs
- [ ] Add OC infrastructure abstractions docs
- [ ] Add OC liquid abstractions docs
- [x] Add OC localization abstractions docs #4869
- [ ] Add OC lucene abstractions docs
- [ ] Add OC media abstractions docs
- [ ] Add OC menu abstractions docs
- [ ] Add OC meta weblog abstractions docs
- [ ] Add OC queries abstractions docs
- [ ] Add OC recipes abstractions docs
- [ ] Add OC resource management abstractions docs
- [x] Add OC setup abstractions docs #4937
- [x] Add OC users abstractions docs #5047
- [ ] Add OC workflows abstractions docs
- [ ] Add OC xml rpc abstractions docs
- [ ] Add OC graph QL client docs
- [ ] Add OC content management docs
- [ ] Add OC content management display docs
- [ ] Add OC content management graph QL docs
- [ ] Add OC contents core docs
- [x] Add OC data docs #4918
- [ ] Add OC deployment core docs
- [ ] Add OC display management docs
- [ ] Add OC display management liquid docs
- [ ] Add OC feeds core docs
- [ ] Add OC fileStorage azure blob docs
- [ ] Add OC fileStorage fileSystem docs
- [ ] Add OC hosting console docs
- [ ] Add OC infrastructure docs
- [x] Add OC localization core docs  #4869
- [ ] Add OC logging nlog docs
- [ ] Add OC logging serilog docs
- [ ] Add OC lucene core docs
- [ ] Add OC mdeia core docs
- [ ] Add OC media services docs
- [ ] Add OC mvc core docs
- [ ] Add OC navigation core docs
- [ ] Add OC openId.Core.EF docs
- [ ] Add OC openId.Core docs
- [ ] Add OC recaptcha core docs
- [ ] Add OC recipes core docs
- [ ] Add OC resource management docs
- [ ] Add OC scripting.JavaScript docs
- [x] Add OC setup core docs  #4937
- [ ] Add OC users core docs

**Comment by agriffard** [comment]
@hishamco All this work would not bring many value compared to the investment that you (and the reviewers) would put into it.
Also, most of the time, it just consists in adding obvious comments above classes, methods or properties.
I really suggest to not make any more PRs of this kind.

**Comment by hishamco** [comment]
It has a value when someone is using the OC binaries

I know it's time consuming, may be a good idea is whenever we create a new class, document it's public APIs

Thanks
