### ISSUE TITLE
RC2 Validation

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#5841]
- [x] Update documentation to mention rc2 packages: #6091
- [x] Set <VersionSuffix>rc2</VersionSuffix> in OrchardCore.Commons.props #6093
- [x] Change docker version in .travis.yml and appveyor.yml #6094
orchardproject/orchardcore-cms-linux:1.0.0-rc2 .;
orchardproject/orchardcore-cms-windows:1.0.0-rc2
- [X] Update module versions (might not be necessary as we did it recently): #5905
- [X] Test templates (tested @deanmarcussen 5/5/2020)
- [x] Create a release/rc2 branch out of dev
  - We might need a custom feed for release branches to test the packages before we merge into master.
- [x] Update .po files on OrchardCore.Translations (PoExtractor) when all PRs are merged (will update Crowdin after a auto-sync)
- [x] Update OrchardCore.Translations to RC2 OrchardCMS/OrchardCore.Translations#47
  - Merge to master to push OrchardCore.Translations.All to NuGet
  - Update OrchardCore.Translations.All version in dependencies.
- [x] Update README.md in release/rc2
- [x] Test guides (with Cloudsmith)
- [x] Merge release/rc2 to master
  - Create a PR
  - Merge Commit (not Squash Merge)
- [x] Test guides (with NuGet)
- [x] Replace rc1-10004 by the new version on NuGet in docs. (in master, with [ci-skip])
- [x] Update and test OrchardCore.Samples
- [x] Close remaining issues for rc2, or assign then to 1.0
- [x] Assign all closed issues from 1.0 and not milestones to rc2
- [x] Tag master with 1.0.0-rc2 (check what we used for rc1)
  - That will create a Release in GH
  - Add a link to the release notes in the documentation
- [x] merge master into dev
- [x] Create release notes in a specific documentation section: #6126
  - Upgrade steps
  - New features
- [x] Create release on GitHub: https://github.com/OrchardCMS/OrchardCore/releases/tag/1.0.0-rc2
- [x] Update https://try.orchardcore.net/
- [x] Blog on devblogs
- [ ] Blog on DNF News
- [x] Tweet

**Comment by Piedone** [comment]
Is there a checklist for publishing a release? I couldn't find any docs on that.

**Comment by sebastienros** [comment]
Let's try to work on one here:
- [ ] Create a release/rc2 branch out of dev
  - We might need a custom feed for release branches to test the packages before we merge into master.
- [ ] Update documentation to mention rc2 packages
- [ ] Update module versions (might not be necessary as we did it recently)
- [ ] Test templates
- [ ] Test guides
- [ ] Close remaining issues for rc2, or assign then to 1.0
- [ ] Assign all closed issues from 1.0 and not milestones to rc2
- [ ] Create release notes in a specific documentation section
  - Upgrade steps
  - New features
- [ ] Merge release/rc2 to master
- [ ] Tag master with 1.0.0-rc2 (check what we used for rc1)
  - That will create a Release in GH
  - Add a link to the release notes in the documentation
- [ ] Test NuGet packages
- [ ] Update website
- [ ] Tweet

**Comment by agriffard** [comment]
[ ] Update https://try.orchardcore.net/

**Comment by hishamco** [comment]
- [x] Update OrchardCore.Transaltions to RC2

**Comment by agriffard** [comment]
A few new features:

- Update to .NET Core 3.1.3
- New orchardcore.net domain
- New documentation structure
- Upgrade to MkDocs Material 5
- New Admin menu structure
- New Admin UI for bulk actions
- Admin templates
- Contributing and Contributors
- Custom admin URL prefix
- Deployment plan Recipe export
- Full-text search enhancements
- Open Tags editor in taxonomies
- Contained item routing
- Content Picker Menu 
- Culture picker on setup page
- Screen setup adapted to small resolutions
- Default pattern for autoroute and alias
- Display mode options
- User disabled/enabled events
- Filter admin menu
- Fix accessibility issues
- Flow editor UI improvements
- Toggle all widgets button
- Sorting items in ListPart
- Retrieve, Update Content workflow task
- Disable and Enable Tenant Workflows Tasks 
- Users change email feature
- Allow Inserting image in HTML
- Themes with vendor- prefix
- ConsoleLog helper
- Preview feature improvement
- Trumbowyg editor, settings and plugins
- Add ability to generate DisplayText with a Pattern
- Database and Azure blob shells configuration
- Disable a user account
- External Login registration without password
- CodeMirror editor for TextField
- Export to json
- Fixing Typos
- Recipe idempotency
- Sitemaps
- Publish later

**Comment by agriffard** [comment]
> We might need a custom feed for release branches to test the packages before we merge into master.

Could we use https://www.myget.org/gallery/orchardcore-dev?

Add it to appveyor.yml instead of orchardcore-preview.

It seems it is only used by OrchardCore.Translations but it would be more coherent to target this one from the dev branch, .
Then we would change in the examples with MyGet in the doc and mention in the release notes that people should now use this feed for dev packages.

**Comment by agriffard** [comment]
Do you have in mind some upgrade steps that we need to mention in the release notes?

/cc @deanmarcussen @jtkech @Skrypt

**Comment by agriffard** [comment]
Suggestion: Use https://github.com/cfpb/github-changelog 

When 1.0.0-rc2 is tagged, execute:
`changelog OrchardCMS OrchardCore 1.0.0-rc1 1.0.0-rc2`
and it will generate changelog between the 2 releases.

**Comment by Skrypt** [comment]
The Lucene index settings are now in the database and the JSON schema has changed so we should advise that people will require to reconfigure their indices.

**Comment by Piedone** [comment]
I've started a documentation page with the aim to have a template and guide for future releases, making releases easier: https://github.com/OrchardCMS/OrchardCore/pull/6119 This then looks like this: 
![image](https://user-images.githubusercontent.com/1976647/81125623-ff286780-8f38-11ea-90c1-2adbae078684.png)


It's mostly elaborating on what's here and making it usable for next releases. I wasn't sure about there to put it so put it under Key Topics, we can move somewhere more appropriate.

I have some questions:

1. What's "Creating templates"? Code generation templates? If yes, where are they?
2. Who has access to the Orchard Twitter?
3. Who has access to the website?
4. What needs to be updated on the website?
5. Who can publish packages on NuGet? Or otherwise, how does that work, isn't it automatically published from Travis, including Translations?

BTW Publish Later is not yet merged (https://github.com/OrchardCMS/OrchardCore/pull/5639) but it was already reviewed by a lot of people so unless anyone has any new objections I'd merge it.

**Comment by jtkech** [comment]
@agriffard on my side nothing i can think of now

**Comment by deanmarcussen** [comment]
@agriffard Nothing here either, except for the change to the default `BagPart` from `Detail` to `Summary` (the original change was the night we did RC1)

**Comment by hishamco** [comment]
@agriffard also

- Email now is differentiate between submitter and sender according to RFC

**Comment by Piedone** [comment]
Found the templates in the meantime. These are published on NuGet with the rest of the packages, right?

**Comment by Piedone** [comment]
Any progress on the remaining tasks? Where can I help the most?

**Comment by Piedone** [comment]
Should this be really closed? It's not fully done. I've updated https://github.com/OrchardCMS/OrchardCore/pull/6119 with the edits from here.

How can blog on the DNF website, who we can get in touch with? Who can blog on DevBlog, @sebastienros @agriffard?

Has anyone tested the guides with NuGet yet? Because I can do that today.

**Comment by sebastienros** [comment]
It was closed in the batch because assigned to rc2. But we know it's not finished. Keep it open of you prefer.

**Comment by Piedone** [comment]
OK. Could you reply to my other questions as well, please?

**Comment by agriffard** [comment]
You can test the guides.

@sebastienros will ask if he can blog on DNF and devblogs.

I guess we could prepare a blogpost (ex: List features https://docs.orchardcore.net/en/dev/docs/releases/1.0.0-rc2/#new-features).
I will try to do a blog section on orchardcore.net also (will look like http://antoinegriffard.com/blog).

**Comment by Piedone** [comment]
Thanks. Tested the guides and updated https://github.com/OrchardCMS/OrchardCore/pull/6119. Also added https://github.com/OrchardCMS/OrchardCore/pull/6415 for some docs fixes.

**Comment by sebastienros** [comment]
Blog post written, @agriffard published it on https://www.orchardcore.net/blog/orchard-core-rc-2 and I am currently submitting it to devblogs.

**Comment by Piedone** [comment]
I've added a note on this to the docs. Why is the blog a separate tenant though?
