### ISSUE TITLE
Let filter & action bars stick on top while scrolling

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#7368]
I already started to make both filter bar and action bar to stick into the top while the page is scrolling, for consistency purpose, I will make the changes in the other admin pages to all of them should have the same experience

- [x] Features Page #7325

- [x] Content Items Page #7336

- [x] Tenants Page #7390

- [x] Content Types Page #7370

- [x] Content Parts Page #7369

- [ ] Edit Template Page

- [x] Recipes Page #7392

- [x] Users Page #7391

**Comment by hishamco** [comment]
@agriffard @Skrypt do you suggest any certain pages or shall I do it across all the list pages?

**Comment by agriffard** [comment]
Some pages like the 'Edit Template' one could have a sticky action buttons bar (bottom or top) when the scroll is too long.

**Comment by agriffard** [comment]
Other pages with list/filter:

- Recipes
- Users

Some pages with few items most of the time:
- Admin menus
- Deployment plans
- Lucene indices
- Queries
- Sitemaps
- Templates
- Workflows

**Comment by hishamco** [comment]
@agriffard Create / Edit:

- Templates

- Queries

may need a lot of thinking, perhaps stick the action button on the bottom is a better choice

**Comment by hishamco** [comment]
Time to close
