### ISSUE TITLE
Admin UI : CORS module

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8195]
**Is your feature request related to a problem? Please describe.**
As reported in #8183 we should enhance this module UI.
It is currently not entirely consistent with what we do in our modules because mainly it uses a Vue.js component to do the entire work.

## TODO

- [ ] Form validations ([VeeValidate](https://vee-validate.logaretm.com/v3)) : same values should not be accepted, empty value should not be accepted.
- [ ] Delete button : should open a modal confirm (No Idea how as of now). Potential solution : ([bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue)).
- [ ] History back after form post throws a ERR_CACHE_MISS browser error (Chrome)
https://stackoverflow.com/questions/62493440/net-core-page-is-not-caching-and-getting-err-cache-miss-error-page-clicking-b
- [ ] Use proper Vue.js routing for history back navigation. When we edit a policy, hitting history back should return you to the policy list instead of the previous controller action made.

**Comment by MatthijsKrempel** [comment]
Will have a look once I get some time.

**Comment by gvkries** [comment]
Related: https://github.com/OrchardCMS/OrchardCore/issues/18552 and https://github.com/OrchardCMS/OrchardCore/pull/18554
